### PR TITLE
Minor edits across five labs.

### PR DESCRIPTION
**Pull request by clifford-smith**
Changes proposed in this pull request:

Module 4 - Edits for grammar, punctuation, and spacing.
Module 8 - Minor changes to PowerShell syntax
Module 9 - Minor grammar and syntax changes. Modified instructions to match interface changes and improve clarity.
Module 10 - Minor edits to match interface changes and correct syntax.
Module 11 - changed powershell to cmd and minor change to match interface.

### CODE REVIEW

**Review by TJGitHubUser — CHANGES_REQUESTED** [review]
Everything looks fine other than some line numbering issues as a result of the changes:

Instructions/Labs/LAB_AK_09_Implementing_RDS_in_Windows_Server.md
Exercise 1, Tasks 1 and 3; please fix the numbering in the instructions

Instructions/Labs/LAB_AK_10_Deploying_network_workloads.md
Exercise 3, Task 1, Task 2

Thanks!

**Comment by clifford-smith** [comment]
Line numbering corrected; streamlined formatting

**Review by TJGitHubUser — COMMENTED** [review]
Line numbering is still a bit off in some places. This is understandably confusing as it's logical to assume that each task is numbered 1 - n. However, there are some sub-procedures within tasks that should be treated as separate procedures.


Instructions/Labs/LAB_AK_10_Deploying_network_workloads.md

Exercise 2, Task 3 - under 'Verify connection on client and VPN server,' the steps should be numbered 1 - 7, and not 7 -13 as it's a separate sub-procedure within the task.

Exercise 3, Task 1 - under 'Verify the Web Server installation.' Renumber steps to be 1 - 4.

Exercise 3, Task 1 - under 'Verify that the Windows Firewall rules for HTTP and HTTPS traffic are enabled.' Renumber steps to be 1 - 4.

Exercise 3, Task 1 - under 'Test the default website.' Renumber steps to be 1 - 6.

Exercise 3, Task 2 - under 'Test the website by using DNS names.' Renumber steps to be 1 - 2.

Exercise 3, Task 2 - under 'Enable remote management of IIS using IIS Manager.' Renumber steps to be 1 - 13.

Exercise 3, Task 2 - under 'Request a new Web Server certificate.' Renumber steps to be 1 - 3.

Instructions/Labs/LAB_AK_09_Implementing_RDS_in_Windows_Server.md

Exercise 1, Task 1, under 'Install RDS using Windows PowerShell,' even though you can use the number 1 only to have it output a seqential numbered list in the markdown, this procedure has a mix of '1' and sequential steps so I think it will be off. Either make it 1 - 9 or use all 1's.

Exercise 1, Task 3, under 'Configure device redirection settings,' renumber steps to be 1 - 11.

Exercise 1, Task 3, under 'Configure User Profile Disks for IT collection,' renumber steps to be 1 - 8.

**Comment by clifford-smith** [comment]
Line numbering corrected; streamlined formatting.

**Review by TJGitHubUser — COMMENTED** [review]
Changes approved, thanks. I will authorize our PDETS team to merge the pull request.

**Pull request merged**
